# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Benson
# email:
description: Web developer and technical writer in Metro Detroit. This is a work in progress. Hello.
permalink: /blog/:title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benson.is" # the base hostname & protocol for your site
twitter_username: johnbenson
github_username:  johnbenson

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
